### ISSUE TITLE
Connection error when the chain instance is restarted

### ISSUE THREAD

**Issue by eduadiez** [swarmcity/SwarmCityAPI#52]
It seems that the API is not able to establish the connection after a restart of the chain instance.

I see the following errors on the API log:

```
api_1    | 2018-01-19T15:09:36.117Z error: jobs/hashtagsIndexer -  {"stack":"Error: connection not open\n    at WebsocketProvider.send (/root/node_modules/web3-providers-ws/src/index.js:219:18)\n    at RequestManager.send (/root/node_modules/web3-core-requestmanager/src/index.js:129:66)\n    at sendRequest (/root/node_modules/web3-core-method/src/index.js:542:42)\n    at Eth.send [as getBlockNumber] (/root/node_modules/web3-core-method/src/index.js:563:13)\n    at getBlockHeight (/root/src/jobs/hashtagsIndexer.js:22:18)\n    at dbService.getLastBlock.then (/root/src/jobs/hashtagsIndexer.js:115:9)","message":"connection not open"}
api_1    | 2018-01-19T15:09:36.117Z error: workerQueue -  task "hashtagIndexerTask" ID=c4e7a4f9-784a-4e52-86da-8d665273f95e" error. Duration 1 ms - Error= {"stack":"Error: connection not open\n    at WebsocketProvider.send (/root/node_modules/web3-providers-ws/src/index.js:219:18)\n    at RequestManager.send (/root/node_modules/web3-core-requestmanager/src/index.js:129:66)\n    at sendRequest (/root/node_modules/web3-core-method/src/index.js:542:42)\n    at Eth.send [as getBlockNumber] (/root/node_modules/web3-core-method/src/index.js:563:13)\n    at getBlockHeight (/root/src/jobs/hashtagsIndexer.js:22:18)\n    at dbService.getLastBlock.then (/root/src/jobs/hashtagsIndexer.js:115:9)","message":"connection not open"}
```

**Comment by koenedaele** [comment]
Looks like web3.js might have had this feature and lost it or will get in again in the future: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-ws/src/index.js#L209

**Comment by BvL13** [comment]
Please clean up this issue and define which epic it belongs to.
